@startuml

skinparam class {
  backgroundColor lightgoldenrodyellow
  arrowColor darkgoldenrod
  borderColor darkgoldenrod
}

class Waiter {
  - cook: Cook
  - barista: Barista
  constructor(cook?: Cook, barista?: Barista)
  + fillOrder(): string
}

class Cook {

}

class Barista {

}

@enduml
