@startuml

interface Strategy {
  chooseLineup(players: string[]): string[]
}

class Team {
  - strategy: Strategy
  constructor(private strategy: Strategy)
  + setStrategy(strategy: Strategy): void
  + prepareLineup(): string[]
}

class DefensiveStrategy {
  + chooseLineup(players: string[]): string[]
}

class OffensiveStrategy {
  + chooseLineup(players: string[]): string[]
}

Strategy <-o Team

Strategy <|.. DefensiveStrategy
Strategy <|.. OffensiveStrategy

@enduml

' prepareLineup() may be client logic
' prepareLineup() can have parameters which are input data for concrete strategies
