@startuml

skinparam class {
  backgroundColor whitesmoke
  arrowColor dimgrey
  borderColor dimgrey
}

interface Builder {
  withEngine(engine: string): void
  withPrice(price: number): void
}

class Manager <OPT> {
  - builder: Builder
  + setBuilder(builder: Builder): void
  + manageBasicVersion(): void
  + managePremiumVersion(): void
}

class Designer <PRE> {
  - car: Car
    constructor()
  + withEngine(engine: string): void
  + withPrice(price: number): void
  + putCarIntoUse(): Car
}

class Car {
  - engine: string
  - price: number
  + setEngine(engine: string): void
  + setPrice(price: number): void
}

Builder <-o Manager
Builder <|.. Designer
Designer -> Car

@enduml

' Manager class is optional
