@startuml

skinparam class {
  backgroundColor whitesmoke
  arrowColor dimgrey
  borderColor dimgrey
}

interface Builder {
  buildWithElevator(): void
  buildWithPool(size: string): void
}

class Director <OPT> {
  - builder: Builder
  + setBuilder(builder: Builder): void
  + manageBasicVersion(): void
  + managePremiumVersion(): void
}

class Contractor <PRE> {
  - house: House
    constructor() {}
  + buildWithElevator(): void
  + buildWithPool((size: string): void
  + putHouseIntoUse(): House
}

class House {
  - equipments: string[]
  + addEquipment(equipment: string): void
  + getEquipments(): string[]
}

Builder <-o Director
Builder <|.. Contractor
Contractor -> House

@enduml

' Director class is optional
