@startuml

skinparam class {
  backgroundColor whitesmoke
  arrowColor dimgrey
  borderColor dimgrey
}

class King <PRE> {
  - {static} instance: King
  - constructor()
  + {static} getInstance(): King
  + showKingName(): string
}

King <- King

@enduml

` showKingName() function is a business logic
